version: '3.8'

x-airflow-common: &airflow-common
  #image: apache/airflow:2.8.0-python3.11
  build: .
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres/${POSTGRES_DB:-airflow}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY:-}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW__CORE__TEST_CONNECTION: Enabled
    # Databricks
    DATABRICKS_HOST: ${DATABRICKS_HOST:-}
    DATABRICKS_TOKEN: ${DATABRICKS_TOKEN:-}
    DATABRICKS_CLUSTER_ID: ${DATABRICKS_CLUSTER_ID:-}
    DATABRICKS_WORKSPACE_PATH: ${DATABRICKS_WORKSPACE_PATH:-}
    AIRFLOW_CONN_DATABRICKS_DEFAULT: databricks://@${DATABRICKS_HOST:-}?token=${DATABRICKS_TOKEN:-}
    OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-}
    OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS:-}
    # Azure Data Lake
    AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-}
    AZURE_STORAGE_KEY: ${AZURE_STORAGE_KEY:-}
    AZURE_CONTAINER: ${AZURE_CONTAINER:-pos-data}
    AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-}
    # Redshift
    REDSHIFT_HOST: ${REDSHIFT_HOST:-}
    REDSHIFT_PORT: ${REDSHIFT_PORT:-5439}
    REDSHIFT_DB: ${REDSHIFT_DB:-food_sales_db}
    REDSHIFT_USER: ${REDSHIFT_USER:-admin}
    REDSHIFT_PASSWORD: ${REDSHIFT_PASSWORD:-}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts
    - ./config:/opt/airflow/config
    - ./Feature_transformation:/opt/airflow/Feature_transformation
    - ../ml-model:/opt/ml-model
    - airflow-logs:/opt/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      POSTGRES_DB: ${POSTGRES_DB:-airflow}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-airflow}"]
      interval: 10s
      retries: 5
    


  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        airflow users create \
          --username ${AIRFLOW_ADMIN_USER:-admin} \
          --password ${AIRFLOW_ADMIN_PASSWORD:-admin} \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

volumes:
  postgres-data:
  airflow-logs:
